backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: "https://ktbmedia.eu"
display_url: "https://ktbmedia.eu"

collections:
  - name: "site"
    label: "Strona"
    files:
      - file: "content/site.json"
        label: "Treści strony"
        name: "site"
